services:
  - type: web
    name: hailin-alumni-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TOKEN_SECRET
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: PUBLIC_SITE_URL
        sync: false
      - key: WECHAT_APPID
        sync: false
      - key: WECHAT_SECRET
        sync: false
      - key: WECHAT_TEMPLATE_ID
        sync: false